[package]
name = "bevy_flappy_bird"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "9ef840e" }
rand = "0.8"

[profile.dev.package."*"]
opt-level = 3
